name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        working-directory: crates/file-info/
        run: cargo build

      - name: Test
        working-directory: crates/file-info/
        run: cargo test
